/* Generated By:JavaCC: Do not edit this line. AxionDateTimeFormatParserConstants.java */
package org.axiondb.parser;

public interface AxionDateTimeFormatParserConstants {

  int EOF = 0;
  int WEEKDAY = 1;
  int WEEKDAY3 = 2;
  int WEEKDAY_FULL = 3;
  int JULIAN_DAY = 4;
  int DAY = 5;
  int MONTH = 6;
  int MONTH_3 = 7;
  int MONTH_FULL = 8;
  int YEAR = 9;
  int YEAR_2 = 10;
  int ERA = 11;
  int HOUR12 = 12;
  int HOUR24 = 13;
  int HOUR12_PADDED = 14;
  int HOUR24_PADDED = 15;
  int MINUTE = 16;
  int SECOND = 17;
  int WEEK = 18;
  int QUARTER = 19;
  int MILLISECOND = 20;
  int AMPM = 21;
  int COMMA = 22;
  int COLON = 23;
  int SEMICOLON = 24;
  int DOT = 25;
  int OPENPAREN = 26;
  int CLOSEPAREN = 27;
  int DASH = 28;
  int SOLIDUS = 29;
  int ISO9660_T = 30;
  int WS = 31;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\"dow\"",
    "\"dy\"",
    "\"day\"",
    "\"ddd\"",
    "\"dd\"",
    "\"mm\"",
    "\"mon\"",
    "\"month\"",
    "\"yyyy\"",
    "\"yy\"",
    "\"bc\"",
    "\"hh\"",
    "\"h\"",
    "\"hh12\"",
    "\"hh24\"",
    "\"mi\"",
    "\"ss\"",
    "\"w\"",
    "\"q\"",
    "\"ff\"",
    "\"am\"",
    "\",\"",
    "\":\"",
    "\";\"",
    "\".\"",
    "\"(\"",
    "\")\"",
    "\"-\"",
    "\"/\"",
    "\"T\"",
    "\" \"",
  };

}

